### ISSUE TITLE
`is_primary` boolean for Monitor objects

### ISSUE THREAD

**Issue by cedric-romain** [rr-/screeninfo#52]
Hello everyone,

I am interested in using this code in a project of mine, however, I would need a way to recognize the primary displays of a user.
My idea was to add a `is_primary` boolean for Monitor objects which is returned when calling the `get_monitors()` function.

If this is something you approve of, I would implement this for all the supported environments and create a pull request. If not, I would simply fork this and add the functionality on my own.

Thank you and have a nice day

**Comment by rr-** [comment]
Since it's a backwards-compatible feature I don't see why we couldn't adapt it. In case the property is unavailable, I think we had a policy that we simply set it to `None`, so if for any reason a given enumerator has no knowledge whether a screen is primary, please set it to `None` rather than `False`.

**Comment by cedric-romain** [comment]
Okay cool. I will try and implement that. You'll hear from me within the next few days.
